export const dummyDataList = [
  {
    id: 1,
    name: "User 1's Title",
    title: "Lego",
    productname: "Lego spike essential",
    price: "700",
    monthprice: "1000",
    age: "6-7",
    classes: "15",
  },
  {
    id: 2,
    name: "User 1's Title",
    title: "Lego",
    productname: "Lego spike essential",
    price: "700",
    monthprice: "1000",
    age: "6-7",
    classes: "15",
  },
  {
    id: 3,
    name: "User 1's Title",
    title: "Lego",
    productname: "Lego spike essential",
    price: "700",
    monthprice: "1000",
    age: "6-7",
    classes: "15",
  },
  {
    id: 4,
    name: "User 1's Title",
    title: "Lego",
    productname: "Lego spike essential",
    price: "700",
    monthprice: "1000",
    age: "6-7",
    classes: "15",
  },
  {
    id: 5,
    name: "User 1's Title",
    title: "Lego",
    productname: "Lego spike essential",
    price: "700",
    monthprice: "1000",
    age: "6-7",
    classes: "15",
  },
];
